#!/usr/bin/env python3
"""Filter to convert YAML formatted JSON schema to JSON."""

import json
import sys

import yaml

__author__ = 'Murray Andrews'


# ------------------------------------------------------------------------------
def main() -> int:
    """Show time."""

    if len(sys.argv) > 1:
        print('Convert YAML formatted JSON schema to JSON', file=sys.stderr)
        print(f'Usage: {sys.argv[0]} < x.yaml > x.json')
        return 1

    d = yaml.safe_load(sys.stdin)

    # If the $id ends in .yaml adjust it to .json.
    if schema_id := d.get('$id'):
        prefix, suffix = schema_id.rsplit('.', 1)
        if suffix == 'yaml':
            d['$id'] = f'{prefix}.json'

    json.dump(d, sys.stdout, indent=4, sort_keys=True)
    print('')
    return 0


# ------------------------------------------------------------------------------
if __name__ == '__main__':

    try:
        sys.exit(main())
    except Exception as e:
        print(e, file=sys.stderr)
        sys.exit(1)
