#!/usr/bin/env python3
"""Filter to convert YAML to JSON."""

import json
import sys

import yaml

__author__ = 'Murray Andrews'


# ------------------------------------------------------------------------------
def main() -> int:
    """Show time."""

    if len(sys.argv) > 1:
        print('Convert YAML to JSON', file=sys.stderr)
        print(f'Usage: {sys.argv[0]} < x.yaml > x.json')
        return 1

    d = yaml.safe_load(sys.stdin)
    json.dump(d, sys.stdout, indent=4, sort_keys=True)
    print('')
    return 0


# ------------------------------------------------------------------------------
if __name__ == '__main__':

    try:
        sys.exit(main())
    except Exception as e:
        print(e, file=sys.stderr)
        sys.exit(1)
